<?php
\ebi\Flow::app([
	'plugins'=>'ebi.flow.plugin.Xml',
	'error_tempalte'=>'ERROR_TEMP.html',
	'patterns'=>[
		''=>['template'=>'index.html'],
		'hoge'=>['template'=>'index.html'],
		'xyz'=>['name'=>'XYZ','template'=>'xyz.html'],
		'secure'=>['name'=>'secure','template'=>'secure.html','secure'=>true],
		'nosecure'=>['name'=>'nosecure','template'=>'secure.html'],
		'noresult'=>['name'=>'noresult'],
		'automap'=>['action'=>'test.flow.AutoAction','name'=>'autoaction'],
	]
]);
